import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import MainContext from "@/context/MainContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-neutral-900">
        <MainContext>
          <div className="h-screen w-full overflow-hidden">
              <NavBar />
            {children}
          </div>
        </MainContext>
      </body>
    </html>
  );
}
